export const brazilianBanks = [
  { code: '001', name: 'Banco do Brasil S.A.' },
  { code: '033', name: 'Banco Santander (Brasil) S.A.' },
  { code: '104', name: 'Caixa Econômica Federal' },
  { code: '237', name: 'Banco Bradesco S.A.' },
  { code: '341', name: 'Banco Itaú S.A.' },
  { code: '077', name: 'Banco Inter S.A.' },
  { code: '260', name: 'Nu Pagamentos S.A. (Nubank)' },
  { code: '070', name: 'BRB - Banco de Brasília S.A.' },
  { code: '290', name: 'PagSeguro Internet S.A.' },
  { code: '323', name: 'Mercado Pago' },
  { code: '380', name: 'PicPay Servicos S.A.' },
  { code: '422', name: 'Banco Safra S.A.' },
  { code: '745', name: 'Banco Citibank S.A.' },
  { code: '756', name: 'Banco Cooperativo do Brasil S.A. - BANCOOB' },
  { code: '748', name: 'Banco Cooperativo Sicredi S.A.' },
  { code: '208', name: 'Banco BTG Pactual S.A.' },
  { code: '212', name: 'Banco Original S.A.' },
  { code: '389', name: 'Banco Mercantil do Brasil S.A.' },
  { code: '633', name: 'Banco Rendimento S.A.' },
  { code: '336', name: 'Banco C6 S.A.' },
  { code: '735', name: 'Banco Neon S.A.' },
  { code: '197', name: 'Stone Pagamentos S.A.' },
  { code: '102', name: 'XP Investimentos' },
  { code: '003', name: 'Banco da Amazônia S.A.' },
  { code: '004', name: 'Banco do Nordeste do Brasil S.A.' },
  { code: '012', name: 'Banco Inbursa S.A.' },
  { code: '021', name: 'BANESTES S.A. Banco do Estado do Espírito Santo' },
  { code: '025', name: 'Banco Alfa S.A.' },
  { code: '036', name: 'Banco Bradesco BBI S.A.' },
  { code: '041', name: 'Banco do Estado do Rio Grande do Sul S.A.' },
  { code: '047', name: 'Banco do Estado de Sergipe S.A.' },
  { code: '062', name: 'Hipercard Banco Múltiplo S.A.' },
  { code: '063', name: 'Banco Bradescard S.A.' },
  { code: '065', name: 'Banco Andbank (Brasil) S.A.' },
  { code: '069', name: 'Banco Crefisa S.A.' },
  { code: '074', name: 'Banco J. Safra S.A.' },
  { code: '082', name: 'Banco Topázio S.A.' },
  { code: '083', name: 'Banco da China Brasil S.A.' },
  { code: '085', name: 'Ailos' },
  { code: '089', name: 'Credisan' },
  { code: '091', name: 'Unicred Central' },
  { code: '092', name: 'BRK S.A.' },
  { code: '093', name: 'Polocred' },
  { code: '094', name: 'Banco Finaxis S.A.' },
  { code: '095', name: 'Banco Confidence de Câmbio S.A.' },
  { code: '096', name: 'Banco BMFBovespa' },
  { code: '097', name: 'CentralCred' },
  { code: '098', name: 'Credialiança' },
  { code: '099', name: 'Uniprime Central' },
  { code: '121', name: 'Banco Agibank S.A.' },
  { code: '125', name: 'Plural S.A.' },
  { code: '184', name: 'Banco Itaú BBA S.A.' },
  { code: '204', name: 'Banco Bradesco Cartões S.A.' },
  { code: '213', name: 'Banco Arbi S.A.' },
  { code: '217', name: 'Banco John Deere S.A.' },
  { code: '218', name: 'Banco BS2 S.A.' },
  { code: '222', name: 'Banco Credit Agrícole Brasil S.A.' },
  { code: '224', name: 'Banco Fibra S.A.' },
  { code: '233', name: 'Banco Cifra S.A.' },
  { code: '241', name: 'Banco Clássico S.A.' },
  { code: '243', name: 'Banco Máxima S.A.' },
  { code: '246', name: 'Banco ABC Brasil S.A.' },
  { code: '249', name: 'Banco Investcred S.A.' },
  { code: '250', name: 'BCV - Banco de Crédito e Varejo S.A.' },
  { code: '253', name: 'Bexs Corretora de Câmbio S/A' },
  { code: '254', name: 'Paraná Banco S.A.' },
  { code: '265', name: 'Banco Fator S.A.' },
  { code: '266', name: 'Banco Cédula S.A.' },
  { code: '268', name: 'Barigui' },
  { code: '269', name: 'HSBC Brasil S.A.' },
  { code: '271', name: 'IB Cctvm S.A.' },
  { code: '300', name: 'Banco de La Nacion Argentina' },
  { code: '318', name: 'Banco BMG S.A.' },
  { code: '320', name: 'China Construction Bank (Brasil)' },
  { code: '348', name: 'Banco XP S.A.' },
  { code: '366', name: 'Banco Société Générale Brasil S.A.' },
  { code: '370', name: 'Banco Mizuho do Brasil S.A.' },
  { code: '376', name: 'Banco J. P. Morgan S.A.' },
  { code: '394', name: 'Banco Bradesco Financiamentos S.A.' },
  { code: '399', name: 'Kirton Bank S.A.' },
  { code: '412', name: 'Banco Capital S.A.' },
  { code: '453', name: 'Banco Rural S.A.' },
  { code: '456', name: 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.' },
  { code: '464', name: 'Banco Sumitomo Mitsui Brasileiro S.A.' },
  { code: '473', name: 'Banco Caixa Geral - Brasil S.A.' },
  { code: '477', name: 'Citibank N.A.' },
  { code: '479', name: 'Banco ItauBank S.A' },
  { code: '487', name: 'Deutsche Bank S.A.' },
  { code: '488', name: 'JPMorgan Chase Bank' },
  { code: '492', name: 'ING Bank N.V.' },
  { code: '494', name: 'Banco de La Republica Oriental del Uruguay' },
  { code: '495', name: 'Banco de La Provincia de Buenos Aires' },
  { code: '505', name: 'Banco Credit Suisse (Brasil) S.A.' },
  { code: '600', name: 'Banco Luso Brasileiro S.A.' },
  { code: '604', name: 'Banco Industrial do Brasil S.A.' },
  { code: '610', name: 'Banco VR S.A.' },
  { code: '611', name: 'Banco Paulista S.A.' },
  { code: '612', name: 'Banco Guanabara S.A.' },
  { code: '613', name: 'Omni Banco S.A.' },
  { code: '623', name: 'Banco PAN S.A.' },
  { code: '626', name: 'Banco Ficsa S.A.' },
  { code: '630', name: 'Banco Intercap S.A.' },
  { code: '634', name: 'Banco Triângulo S.A.' },
  { code: '637', name: 'Banco Sofisa S.A.' },
  { code: '641', name: 'Banco Alvorada S.A.' },
  { code: '643', name: 'Banco Pine S.A.' },
  { code: '652', name: 'Itaú Unibanco Holding S.A.' },
  { code: '653', name: 'Banco Indusval S.A.' },
  { code: '654', name: 'Banco A.J.Renner S.A.' },
  { code: '655', name: 'Banco Votorantim S.A.' },
  { code: '707', name: 'Banco Daycoval S.A.' },
  { code: '739', name: 'Banco Cetelem S.A.' },
  { code: '741', name: 'Banco Ribeirão Preto S.A.' },
  { code: '743', name: 'Banco Semear S.A.' },
  { code: '746', name: 'Banco Modal S.A.' },
  { code: '747', name: 'Banco Rabobank International Brasil S.A.' },
  { code: '751', name: 'Scotiabank Brasil S.A.' },
  { code: '752', name: 'Banco BNP Paribas Brasil S.A.' },
  { code: '753', name: 'Novo Banco Continental S.A.' },
  { code: '754', name: 'Sistema Cooperativo de Crédito' },
  { code: '755', name: 'Bank of America Merrill Lynch' },
].sort((a, b) => a.name.localeCompare(b.name));

export const commonBanks = [
  { code: '001', name: 'Banco do Brasil' },
  { code: '033', name: 'Santander' },
  { code: '104', name: 'Caixa Econômica' },
  { code: '237', name: 'Bradesco' },
  { code: '341', name: 'Itaú' },
  { code: '077', name: 'Inter' },
  { code: '260', name: 'Nubank' },
  { code: '336', name: 'C6 Bank' },
  { code: '290', name: 'PagSeguro' },
  { code: '323', name: 'Mercado Pago' },
];

export function getBankByCode(code: string): { code: string; name: string } | undefined {
  return brazilianBanks.find((bank) => bank.code === code);
}

export function searchBanks(query: string): Array<{ code: string; name: string }> {
  const lowerQuery = query.toLowerCase();
  return brazilianBanks.filter(
    (bank) => bank.code.includes(query) || bank.name.toLowerCase().includes(lowerQuery)
  );
}
