#!/bin/bash
echo "=== REMOVENDO CONFIGURAÇÕES DO NEON ==="
echo ""
echo "⚠️  ATENÇÃO: Este script irá:"
echo "1. Listar todas as referências ao Neon"
echo "2. Sugerir comandos para remover o banco Neon"
echo ""

echo "📍 Configurações atuais que precisam ser alteradas:"
echo "DATABASE_URL: $(echo $DATABASE_URL | grep -o 'neon' && echo '❌ Aponta para Neon' || echo '✅ OK')"
echo "PGHOST: $(echo $PGHOST | grep -o 'neon' && echo '❌ Aponta para Neon' || echo '✅ OK')"
echo ""

echo "📌 Para corrigir manualmente:"
echo "1. Vá em Replit → Tools → Database"
echo "2. Delete o banco 'PostgreSQL (Neon)'"
echo "3. Vá em Tools → Secrets"
echo "4. Atualize DATABASE_URL com a URL do Supabase"
echo ""
echo "URL correta do Supabase deve ser:"
echo "postgresql://postgres.dvglgxrvhmtsixaabxha:[SENHA]@aws-0-us-east-1.pooler.supabase.com:6543/postgres"
